#!/bin/bash
sudo rm -rf /usr/bin/amd-gpu-run
sudo rm -rf /usr/bin/game-run
sudo rm -rf /usr/bin/intel-gpu-run
sudo rm -rf /usr/bin/killpicom
sudo rm -rf /usr/bin/nouveau-gpu-run
sudo rm -rf /usr/bin/nvidia-gpu-run
sudo rm -rf /etc/conf.d/libvirt-guests
sudo rm -rf /etc/environment.d/editor.conf
sudo rm -rf /etc/grub.d/40_cpu_mitigations.cfg
sudo rm -rf /etc/grub.d/40_distrust_cpu.cfg
sudo rm -rf /etc/grub.d/40_enable_iommu.cfg
sudo rm -rf /etc/modprobe.d/amdgpu.conf
sudo rm -rf /etc/modprobe.d/blacklist.conf
sudo rm -rf /etc/modprobe.d/kvmfr.conf
sudo rm -rf /etc/modprobe.d/nvidia.conf
sudo rm -rf /etc/modprobe.d/v4l2loopback.conf
sudo rm -rf /etc/modules-load.d/kvmfr.conf
sudo rm -rf /etc/modules-load.d/v4l2loopback.conf
sudo rm -rf /etc/modules-load.d/zram.conf
sudo rm -rf /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
sudo rm -rf /etc/sysctl.d/80-gamecompatibility.conf
sudo rm -rf /etc/systemd/coredump.conf.d/disable.conf
sudo rm -rf /etc/systemd/journald.conf.d/00-journal-size.conf
sudo rm -rf /etc/systemd/system/battery_charge_threshold.service
sudo rm -rf /etc/systemd/system/user@.service.d/99-reduce-time.conf
sudo rm -rf /etc/systemd/system.conf.d/00-timeout.conf
sudo rm -rf /etc/udev/rules.d/40-hpet-permissions.rules
sudo rm -rf /etc/udev/rules.d/50-sata.rules
sudo rm -rf /etc/udev/rules.d/60-ioschedulers.rules
sudo rm -rf /etc/udev/rules.d/60-sunshine.rules
sudo rm -rf /etc/udev/rules.d/71-nvidia.rules
sudo rm -rf /etc/udev/rules.d/90-arduino.rules
sudo rm -rf /etc/udev/rules.d/99-cpu-freq.rules
sudo rm -rf /etc/udev/rules.d/99-intel-cpu-watts-fix.rules
sudo rm -rf /etc/udev/rules.d/99-ntfs3_by_default.rules
sudo rm -rf /etc/udev/rules.d/99-ntsync.rules
sudo rm -rf /etc/udisks2/mount_options.conf
sudo rm -rf /etc/chrony.conf
sudo rm -rf /etc/makepkg.conf.d/use-all-cores.conf
sudo rm -rf /etc/polkit-1/rules.d/99-shutdown-reboot.rules